### ISSUE TITLE
WIN32 build doesn't work - missing ./config ?!

### ISSUE THREAD

**Issue by labba** [arizvisa/afl-cygwin#2]
while trying to build in cygwin, i have activated the cygwinserver-config and then when trying to run the Makefile as WIN32 defined i'm getting this error during the make (i have added the echo off prints as well):

$ make
Makefile:177: warning: overriding recipe for target 'test_build'
Makefile:122: warning: ignoring old recipe for target 'test_build'
echo "[_] Checking for the ability to compile x86 code..."
[_] Checking for the ability to compile x86 code...
echo 'main() { **asm**("xorb %al, %al"); }' | cc -w -x c - -o .test || ( echo; echo "Oops, looks like your compiler can't generate x86 code."; echo; echo "You can still try using the LLVM or QEMU mode, but see docs/INSTALL first."; echo "To ignore this error, set AFL_NOX86=1."; echo; exit 1 )
rm -f .test
echo "[+] Everything seems to be working, ready to compile."
[+] Everything seems to be working, ready to compile.
echo "[_] Compiling afl-gcc.c to afl-gcc.o"
[_] Compiling afl-gcc.c to afl-gcc.o
cc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DDOC_PATH=\"/usr/local/share/doc/afl\" -DBIN_PATH=\"/usr/local/bin\" -DVERSION=\"1.83b\" -D_WIN32 -include winapi.h -c afl-gcc.c -o afl-gcc.o
afl-gcc.c: In function ‘main’:
afl-gcc.c:307:5: warning: implicit declaration of function ‘scream_parameters’ [-Wimplicit-function-declaration]
     scream_parameters(cc_params);
     ^
afl-gcc.c: At top level:
afl-gcc.c:316:1: warning: conflicting types for ‘scream_parameters’
 scream_parameters(char*\* parms)
 ^
afl-gcc.c:307:5: note: previous implicit declaration of ‘scream_parameters’ was here
     scream_parameters(cc_params);
     ^
cc   afl-gcc.o   -o afl-gcc
echo "[_] Compiling afl-as.c to afl-as.o"
[_] Compiling afl-as.c to afl-as.o
cc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DDOC_PATH=\"/usr/local/share/doc/afl\" -DBIN_PATH=\"/usr/local/bin\" -DVERSION=\"1.83b\" -D_WIN32 -include winapi.h -c afl-as.c -o afl-as.o
afl-as.c: In function ‘main’:
afl-as.c:521:13: warning: assignment makes integer from pointer without a cast
   if (!(pid = fork())) {
             ^
afl-as.c:530:15: warning: passing argument 1 of ‘native_waitpid’ makes pointer from integer without a cast
   if (waitpid(pid, &status, 0) <= 0) PFATAL("waitpid() failed");
               ^
In file included from <command-line>:0:0:
./winapi.h:40:8: note: expected ‘_pid_t’ but argument is of type ‘s32’
 _pid_t native_waitpid(_pid_t, int_, int);
        ^
cc   afl-as.o   -o afl-as
afl-as.o: In function `main':
/cygdrive/c/Work/Tools/afl-cygwin/afl-as.c:521: undefined reference to`native_fork'
/cygdrive/c/Work/Tools/afl-cygwin/afl-as.c:521:(.text.startup+0x4fc): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `native_fork'
/cygdrive/c/Work/Tools/afl-cygwin/afl-as.c:530: undefined reference to`native_waitpid'
/cygdrive/c/Work/Tools/afl-cygwin/afl-as.c:530:(.text.startup+0x51a): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `native_waitpid'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'afl-as' failed
make: *_\* [afl-as] Error 1

why there is no ./config file for the cygwin env ? how this should work ? no read me on how to compile this into win32 or to replace for now the cov with PIN trace

**Comment by arizvisa** [comment]
Try make WIN32=1. Each time it links, the binary is supposed to link with winapi.o if that's what you're doing then my Makefile sucks.

So, everytime you see something like the following without winapi.o being there as one of the object files you're likely to see an "undefined symbol" error. winapi.h uses the cpp to wrap the posix apis, and winapi.o contains their implementations.
cc afl-as.o -o afl-as
should be:
cc afl-as.o -o afl-as winapi.o

You can probably manually link each binary with that object to get it to use the correct wrappers. So, with regards to the build failing, I define winapi.o as one of the dependencies expecting $^ to pick it up, but for some reason it's not working on your system (most probably more than yours?).

This is the build rule in the Makefile that should be getting evaluated.
afl-as.exe: afl-as.o winapi.o
    $(CC) $(CFLAGS) $^ -o $@ $(LDFLAGS)
    ln -sf afl-as as

Anyways, sorry for there being no README  (or youtube video on replacing the cov with PIN since umm..this project doesn't actually have anything to do with PIN) as since there's more to bugs than just fuzzing I put this project down due to being knee deep in something else...but as per renewed interest and also vh's issue #1, I'm currently working on a branch that upgrades afl-cygwin from afl-1.83b to using afl-1.96b as well as splitting branches for native forking and cygwin's slow-forking which I'll be committing soon. I'll try and resolve any weird build problems that you post up here too.

Thanks.

**Comment by labba** [comment]
thanks! looking forward with your future build. are you also going to add PIN of DynamoRIO or the Intel PT as a coverage solution to make it a real port ? or still it can only run as a afl-cygwin with "-n" for dumb?

**Comment by arizvisa** [comment]
Nah, this project isn't related to PIN or DynamoRIO and hence isn't a modification of how AFL's instrumentation actually works. I left it the way lcamtuf did it (which patches all the labels via hooking the assembling stage). This way you can run it as dumb or not, but in order to instrument you're still left needing the source-code in order to build the instrumented version of your target.

This project doesn't really modify any of the functionality that afl has already implemented. All it does is emulate (as best as possible via winapi.c) the posix api's that cygwin doesn't implement entirely, fix the Makefile to use proper dependency resolution, and wrap the explicit calls in the injected assembler to the posix ones. So just a straight-up port to the native windows api.

If you're looking for modifying the way that instrumentation works for afl, there's a sub-project that's part of moflow that uses dyninst to do it. If you go here https://github.com/vrtadmin/moflow/tree/master/afl-dyninst, that'll do instrumentation on Windows.

**Comment by labba** [comment]
so your future version of AFL-cygwin on windows fork (that currently doesn't work on window) will work with the dyninst one ?

**Comment by labba** [comment]
hi,
i have re-make on a clean system and i acctually found that the issue is with:

%.o: %.c
	@echo "[*] Compiling $< to $@"
	$(CC) $(CFLAGS) -c $< -o $@

this line cause the try of compilation of all file without the required winapi.o

**Comment by arizvisa** [comment]
This project and the dyninst project are two different ones with two different intentions. When I finish my current work project and get around to committing the next version of afl-cygwin for afl-1.96b, you're more than welcome to merge the two entirely different projects and maintain it. ;-)

**Comment by arizvisa** [comment]
This should be addressed by commit e9b0fe77b0604aad578b35b0e48a54ef4046433a. The Makefile properly includes winapi.o as a dependency for everything instead of hackishly including it as a commandline flag and stuff.
