### ISSUE TITLE
Win32 fork assertion

### ISSUE THREAD

**Issue by labba** [arizvisa/afl-cygwin#5]
hi,
i have resolved the issue of the make file by changing the make file to create only the afl-fuzz.exe and now when i'm running afl with the winapi i'm getting as flowing:

$ ./afl-fuzz.exe -i ./my_test/input/ -o ./my_test/crashes/ -n ./my_test/copy_it.exe @@
afl-fuzz 1.83b by lcamtuf@google.com
[+] You have 4 CPU cores and 0 runnable tasks (utilization: 0%).
[+] Try parallel jobs - see docs/parallel_fuzzing.txt.
[_] Setting up output directories...
[+] Output directory exists but deemed OK to reuse.
[_] Deleting old session data...
[+] Output dir cleanup successful.
[_] Scanning './my_test/input/'...
[+] No auto-generated dictionary tokens to reuse.
[_] Creating hard links for all input files...
[_] Validating target binary...
[_] Attempting dry run with 'id:000000,orig:input.txt'...
assertion "DuplicateHandle(hCurrentProcess, handle, hChild, &shared->hStdin, 0, TRUE, DUPLICATE_SAME_ACCESS) != 0" failed: file "winapi.c", line 267,
function: _fork_prepare_child

using win7 x64 - cygwing running in admin.

**Comment by arizvisa** [comment]
> i have debugged it a bit and this actually getting here since GetCurrentProcess() failed and returned -1:
> 
> i have added the flowing assert:
> HANDLE hCurrentProcess = GetCurrentProcess();
> if (hCurrentProcess == 0xffffffff)
> assert (0);
> 
> and indeed i got:
> [*] Attempting dry run with 'id:000000,orig:inputtxt'
> assertion "0" failed: file "winapic", line 245, function: _fork_prepare_child

GetCurrentProcess() is supposed to return -1, it's a pseudo-handle as per the sdk documentation.

**Comment by arizvisa** [comment]
For the original problem, can you output the result of DuplicateHandle. And also prefix each DuplicateHandle with an assertion of `assert(handle != INVALID_HANDLE_VALUE)`. This code is supposed to duplicate the console handles for std{in,out,err} into the hChild process so that any children are still able to WriteConsole the parent's console.

**Comment by labba** [comment]
it the first duplicate handle in and i have added the suggested line assertion. this does stop on that assertion. so maybe it is related to how cygwin console (fail also when running bash.exe) is being created (tty or anything like that ?)

**Comment by labba** [comment]
ok i have run mintty with bash as command line and indded it working now. so this was related to how cygwin console is being created.

**Comment by arizvisa** [comment]
Ah, ok. Yeah, cygwin's console + bash was pretty much my development environment hence you having no problems in that environment.

I'm also pretty certain that this would be fixed by the fix for issue #4 since it's related to initializing the newly fork'd process. I'll end up ensuring that cygwin is properly re-initialized in the newly forked process. I had tested this against a pretty dumb native Windows process which is why I never encountered your issue.. Also, was copy_it.exe linked with cygwin or something else?

So just for the sake of completion, can you give me the result of GetLastError() after the call to GetStdHandle(...)? Also, I can assume your test-application copy_it.exe isn't doing anything terminal/console or process-group related such as setsid, setpgid, tc{get,set}*, etc, right?

I'm guessing that due to the way that previous process is fork()d, cygwin caches a handle that it will later set via SetStdHandle(...) on process creation. And so since #4, GetStdHandle(...) returns INVALID_HANDLE_VALUE due to nothing having called SetStdHandle previously unless one is in a cygwin console where the parent would actually have a correct handle. There's also a chance that it might not be cygwin's issue, but both can be fixed by re-opening a handle to the console (if I can prove that the parent process actually set a handle to the parent's console via SetStdHandle) as well as making it non-fatal if the handles are closed (since it's perfectly normal for a process to close it's std{in,out,err}). I incorrectly assumed that a fork()d process would always have an stdin..which is definitely not always the case.

Anyways, after you get me the result of GetLastError() from GetStdHandle(...) and confirmation about copy_it.exe functionality, I'll mark this a dupe of #4.

Thanks for the report!

**Comment by labba** [comment]
hi, thanks for the detailed explanation! 
GetLastError:
for : GetStdHandle - returned 0.
for: DuplicateHandle - returned 87 (ERROR_INVALID_PARAMETER) 

the "copy_it" was compiled under visual studio (like a real scenario that we have a windows binary that wasn't a cygwin compiled application) and doesn't do any terminal/console or process-group related such as setsid, setpgid etc.

**Comment by arizvisa** [comment]
Until I write the patch, you might be able to get away with commenting out the assertions in the code that verifies GetStdHandle(...) != INVALID_HANDLE_VALUE. Thanks!

**Comment by arizvisa** [comment]
This should be covered by commit e9b0fe77b0604aad578b35b0e48a54ef4046433a. If it's not, let me know and I'll re-open the issue.
