### ISSUE TITLE
crash on -.cur_input - File exists

### ISSUE THREAD

**Issue by labba** [arizvisa/afl-cygwin#6]
now that afl-fuzz.exe working well with the winapi (getting 100 test per sec instead of 10) after a while that it runs the fuzzer stops with this issue:

[-]  SYSTEM ERROR : Unable to create './my_test/output/.cur_input'
    Stop location : write_to_testcase(), afl-fuzz.c:2301
       OS message : File exists

there is no file exist in that folder with that name.

**Comment by arizvisa** [comment]
Hmm..seems like a race condition of some kind maybe?. There's a wrapper for open(...) in winapi.c, but it passes files straight through to cygwin's open(...) unless the path is special.

So, the code in afl that's being executed is unlink(filename) followed by open(filename, ...). Unless something is creating the file in-between the unlink(...) and open(...) calls..perhaps another program is somehow forking and the testcase filename is collisioning...

The other situation is that it would appear that unlink(...) is not actually removing that file. It's pretty crazy to think this, but I suppose to debug further you can perhaps verify that the file is actually deleted after the unlink call. There's no 100% way to test this out though until it's proven that there's only 1 task creating the file and unlinking it.

But, if you use sysinternals' process monitor (procmon.exe) to view filesystem activity and set a filter for that process name, one should be able to see any process and a log of any fileops that happen against that path. That should give enough insight into which process is unlinking the file and which one is creating it.

**Comment by arizvisa** [comment]
Have you had a chance to run process monitor and view the filesystem activity?

**Comment by labba** [comment]
no sorry didn't had the chance yet..

**Comment by arizvisa** [comment]
k, let me know if you want to squash that race issue. I'll keep this issue open for a month before I close it.

**Comment by xixabangm4** [comment]
In case this is relevant: http://wiki.osdev.org/Cygwin_Issues
unlink()
unlink isn't atomic (as on other platforms also)
while (!unlink(..) or end-of-waiting()) { sleep; }
On cygwin unlink() is deferred to the end of the process, when unlink fails because of locks or delete on close (ERROR_SHARING_VIOLATION).
unlink a file and subsequent creation of a new file in the same location is not supported.
unlink(2) doesn't do traverse security checks:
cygwin unlink() still has the POSIX bug I reported earlier where calling unlink() on a file in a directory with no write permissions still removes the file, thanks to the underlying Windows implementation. Worse, because the directory has no write permissions, you can't directly re-create a new file to replace the one that was erroneously deleted. But Chris already argued that checking for write permissions on the parent directory as part of every unlink() call would slow down the common case. - EricBlake
http://sourceware.org/ml/cygwin/2005-04/msg00552.html
"delete on close" (unlinking an open file) is supported.
(definitive answer: => pierre)

**Comment by labba** [comment]
verified!   it working now just fine in the latest version you have on git. 
no more bugs in dumb mode

**Comment by arizvisa** [comment]
ok, weird. closing this issue.
