### ISSUE TITLE
Compile issues

### ISSUE THREAD

**Issue by vanhauser-thc** [arizvisa/afl-cygwin#7]
Putting this in the top of afl-gcc.c removes an implicit call warning:
void scream_parameters(char*\* parms);

But compiling fails:

[*] Testing the CC wrapper and instrumentation output...
unset AFL_USE_ASAN AFL_USE_MSAN; AFL_QUIET=1 AFL_INST_RATIO=100 AFL_PATH=. ./afl-gcc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH=\"/usr/local/lib/afl\" -DDOC_PATH=\"/usr/local/share/doc/afl\" -DBIN_PATH=\"/usr/local/bin\" -DVERSION=\"1.96b\" test-instr.c -o test-instr.o
/tmp/cc4L0bmL.o:test-instr.c:(.text+0x3c): undefined reference to `__afl_global_area_ptr@GOTPCREL'
/tmp/cc4L0bmL.o:test-instr.c:(.text+0x3c): relocation truncated to fit: R_X86_64_PC32 against undefined symbol`__afl_global_area_ptr@GOTPCREL'
/tmp/cc4L0bmL.o:test-instr.c:(.text+0x127): undefined reference to `getenv@PLT'
/tmp/cc4L0bmL.o:test-instr.c:(.text+0x127): relocation truncated to fit: R_X86_64_PC32 against undefined symbol`getenv@PLT'

(maybe the source of the issue is that I am using cygwin x64?)

**Comment by arizvisa** [comment]
Oh, weird.

Yeah, I definitely developed it against cygwin-x86. I'll check it against x64.

In the meantime, can you pass the env variable AFL_KEEP_ASSEMBLY=1 to it? It should output a .afl-something.s file to your tmpdir which gets assembled into that obj file. Also, if you remove AFL_QUIET=1, you can see how afl-as is getting called if you're interested, but that .s file that it emits might give some more clarifications on what I busted.

But yeah, give me a bit to install cygwin-x64. I really use msys to do this deving, so my bad heh. ;-)

**Comment by vanhauser-thc** [comment]
I set the AFL_KEEP_ASSEMBLY And removed the AFL_QUIET.

afl-cc 1.96b by lcamtuf@google.com
[+] Executing:
gcc -O3 -funroll-loops -Wall -D_FORTIFY_SOURCE=2 -g -Wno-pointer-sign -DAFL_PATH="/usr/local/lib/afl" -DDOC_PATH="/usr/local/share/doc/afl" -DBIN_PATH="/usr/local/bin" -DVERSION="1.96b" test-instr.c -o test-instr.o -B . -g -O3 -funroll-loops
afl-as 1.96b by lcamtuf@google.com
[+] Instrumented 6 locations (64-bit, non-hardened mode, ratio 100%).
/tmp/ccb6EUFv.o:test-instr.c:(.text+0x3c): undefined reference to `__afl_global_area_ptr@GOTPCREL'
/tmp/ccb6EUFv.o:test-instr.c:(.text+0x3c): relocation truncated to fit: R_X86_64_PC32 against undefined symbol`__afl_global_area_ptr@GOTPCREL'
/tmp/ccb6EUFv.o:test-instr.c:(.text+0x127): undefined reference to `getenv@PLT'

the two .s files are attached in a ZIP

thanks for your effort!

[afl_s.zip](https://github.com/arizvisa/afl-cygwin/files/164734/afl_s.zip)

**Comment by arizvisa** [comment]
So, figured that issue out.

At first I was thinking that it wasn't using callq and so was using the wrong instruction which resulted in the object file using R_X86_64_PC32 as the relo size and perhaps it needed to be a 64-bit relo...but then I realized that it shouldn't matter since the symbols aren't more than 31-bits away...

And so, apparently in order for the linker to create a relocation and allocate a slot in the ".got" (really iat) each symbol has to be explicitly defined as a global. So, a fix is to pretty much define each symbol as a global like in the following within afl-as.h. Not sure why it doesn't have the same issue with elf (or rather vanilla afl) as it does with pe. Maybe we should blame ld. Anyways, this should generate the object file correctly with the plt entries. 

`"/* --- AFL MAIN PAYLOAD (64-BIT) --- */\n"`
`"\n"`
`".text\n"`
`".att_syntax\n"`
`".code64\n"`
`#if defined(__CYGWIN__) || defined(__MSYS__)`
`".globl fork\n"`
`".globl atoi\n"`
`".globl shmat\n"`
`".globl write\n"`
`".globl waitpid\n"`
`".globl close\n"`
`".globl _exit\n"`
`".globl __afl_global_area_ptr\n"`
`#endif`

An alternative solution would be to just not use the plt to call these symbols anyways and modify `CALL_L64` to not call `symbol@PLT` but rather just `symbol`. This results in modifying significantly less of lcamtuf's code, but changes his intentions of using a dereference to get to these symbols. So I think I might go with defining each of these symbols as global.

After doing that, though, I realized that there's still things like the difference in calling convention between sysv and windows-x64 that I neglected to think about as well as there being probably some integer truncation bugs in winapi.c that should prolly get fixed. But, I'm working through them..so I should have a proper patch in a little while.

**Comment by arizvisa** [comment]
Although this is fixed by commit d31a23cbae12b5837811917114347a1ee1cea7cd, you'll actually want commit cc0868a542098275cc09b61c6073ce19863b45c3 which does the transformation of the calling convention and things.

Let me know you encounter any other issues. If not, then in the next commit I'll work on fixing some of the cygwin-specific issues that happen when forking natively.
